name: AndroidBuild
on:
  push:
    branches: [ test ]

jobs:


  check:
    name: Static Checks

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 18

  unit-test:

    needs: check

    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 18

      - name: Run Unit tests
        run: ./gradlew test




