name: AndroidBuild
on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 18 ]
        entry:
            - { mock-maker: 'mock-maker-default', member-accessor: 'member-accessor-default' }
            - { mock-maker: 'mock-maker-inline', member-accessor: 'member-accessor-module' }
            - { mock-maker: 'mock-maker-subclass', member-accessor: 'member-accessor-module' }
            - { mock-maker: 'mock-maker-subclass', member-accessor: 'member-accessor-reflection' }
            - { mock-maker: 'mock-maker-inline', member-accessor: 'member-accessor-reflection' }

    steps:
      #- name: Run tests
      # run: ./gradlew test
      - name: 1. Check out code
        uses: actions/checkout@v4.1.0

      - name: 2. Set up Java for running Gradle build
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '18'
          distribution: 'zulu'

      - name: 3. Validate Gradle wrapper
        if: matrix.java == 11 && matrix.entry.mock-maker == 'mock-maker-default' # SINGLE-MATRIX-JOB
        uses: gradle/wrapper-validation-action@v2.1.1 # https://github.com/gradle/wrapper-validation-action

      - name: 4. Build and check reproducibility of artifacts (single job only)
        if: matrix.java == 11 && matrix.entry.mock-maker == 'mock-maker-default' # SINGLE-MATRIX-JOB
        run: ./check_reproducibility.sh

      - name: 5. Spotless check (single job only). Run './gradlew spotlessApply' locally if this job fails.
        if: matrix.java == 11 && matrix.entry.mock-maker == 'mock-maker-default' # SINGLE-MATRIX-JOB
        run: >
          ./gradlew
          spotlessCheck
          --stacktrace
          --scan

      - name: 6. Build on Java ${{ matrix.java }} with ${{ matrix.entry.mock-maker }} and ${{ matrix.entry.member-accessor }}
        run: >
          ./gradlew
          -Pmockito.test.java=${{ matrix.java }}
          build
          idea
          --stacktrace
          --scan
        env:
          MOCK_MAKER: ${{ matrix.entry.mock-maker }}
          MEMBER_ACCESSOR: ${{ matrix.entry.member-accessor }}

      - name: 7. Generate coverage report
        run: >
          ./gradlew
          -Pmockito.test.java=${{ matrix.java }}
          coverageReport
          --stacktrace
          --scan

